### ISSUE TITLE
How about focussing on just the DSL aspect?

### ISSUE THREAD

**Issue by alloy** [ashkan18/graphlient#12]
GitHub’s [GraphQL client](https://github.com/github/graphql-client) does a lot of things well already (e.g. query/schema validation). It seems like `graphlient` was born out of a want for a Ruby DSL, so how about just focussing on that, but otherwise leverage the excellent work already being done by many maintainers?

Looking at the source of their client, the first thing it does is [parse the query](https://github.com/github/graphql-client/blob/6a20a832d1affd2b1de80ac1dc683accfca3f65b/lib/graphql/client.rb#L151), from then on it basically operates on the AST of the query. You could programatically generate that AST based on your DSL and then hand that off to `graphql-client` to do the rest of the work.

```
$ gem install graphql
Fetching: graphql-1.7.3.gem (100%)
Successfully installed graphql-1.7.3
1 gem installed

$ irb -r graphql
irb(main):001:0> GraphQL.parse <<-GRAPHQL
irb(main):002:0"   query {
irb(main):003:0"     luke: human(id: "1000") {
irb(main):004:0"       name
irb(main):005:0"     }
irb(main):006:0"     leia: human(id: "1003") {
irb(main):007:0"       name
irb(main):008:0"     }
irb(main):009:0"   }
irb(main):010:0" GRAPHQL
=> #<GraphQL::Language::Nodes::Document:0x007ffd86029a50 @filename=nil, @definitions=[#<GraphQL::Language::Nodes::OperationDefinition:0x007ffd86029bb8 @line=1, @col=3, @filename=nil, @operation_type="query", @name=nil, @variables=[], @directives=[], @selections=[#<GraphQL::Language::Nodes::Field:0x007ffd8602b4b8 @line=2, @col=5, @filename=nil, @name="human", @alias="luke", @arguments=[#<GraphQL::Language::Nodes::Argument:0x007ffd8602bc10 @line=2, @col=17, @filename=nil, @name="id", @value="1000">], @directives=[], @selections=[#<GraphQL::Language::Nodes::Field:0x007ffd8602b738 @line=3, @col=7, @filename=nil, @name="name", @alias=nil, @arguments=[], @directives=[], @selections=[]>]>, #<GraphQL::Language::Nodes::Field:0x007ffd8602a1f8 @line=5, @col=5, @filename=nil, @name="human", @alias="leia", @arguments=[#<GraphQL::Language::Nodes::Argument:0x007ffd8602af68 @line=5, @col=17, @filename=nil, @name="id", @value="1003">], @directives=[], @selections=[#<GraphQL::Language::Nodes::Field:0x007ffd8602a8d8 @line=6, @col=7, @filename=nil, @name="name", @alias=nil, @arguments=[], @directives=[], @selections=[]>]>]>]>
```

**Comment by dblock** [comment]
Note that I opened https://github.com/github/graphql-client/issues/126 ;)

**Comment by dblock** [comment]
There're a few visible problems from the GraphQL Github client, including unclear error handling and pretty sizable reinvention of the wheel when it comes to schema parsing. So maybe that part should come from https://github.com/rmosolgo/graphql-ruby and not from a strongly opinionated gem like graphql-client. I'm also generally not happy with using `HTTP`, see https://github.com/ashkan18/graphlient/issues/7

**Comment by alloy** [comment]
I actually don’t see the `grapnel-client` as opinionated, it looks very boring to me… which is a good thing to build on top of!

E.g. they don’t do their own parsing, they literally do what I showed in my irb session; that is, they use https://github.com/rmosolgo/graphql-ruby for all GraphQL schema stuff. Unless you were referring to something else?

I’m sure that the HTTP client aspect is something that could be discussed with the `graphql-client` maintainers.

**Comment by dblock** [comment]
Yeah I spent a whole 5 minutes there, you're right @alloy :)

**Comment by ashkan18** [comment]
Looking deeper at this, it seems to me, it may make more sense to update `GraphQL.parse` method to also accept block. That would be a change in `graphql` and not the `graphql-client` what do you guys think?

**Comment by alloy** [comment]
Why do you think so? I don’t think you need to use the parse function at all, your DSL should just generate an AST like `parse`would generate, then you can just plug that into `graphql-client` and everything should just work.

**Comment by dblock** [comment]
`parse` could be a stopgap quick implementation tho

**Comment by ashkan18** [comment]
Looking at `graphql` and how they parse the string, it may make sense as our first step use their `parser` https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/language/parser.rb which is created using [racc](https://github.com/tenderlove/racc). I can imagine later we can generate our own parser, but for now our problem will limit to read the block and try to create string version of it :)

**Comment by dblock** [comment]
https://github.com/ashkan18/graphlient/pull/14 uses graphql-client, closing
