### ISSUE TITLE
cache schema

### ISSUE THREAD

**Issue by ashkan18** [ashkan18/graphlient#15]
Currently for each call we download schema to be able to validate the query against it. We should cache this and avoid extra calls.

**Comment by dblock** [comment]
That's also why the ruby graphql client forces you to assign the parsed schema and queries to a static member of a module.

**Comment by dblock** [comment]
#25 lets you do exactly the same thing as graphql-client, example in https://github.com/ashkan18/graphlient/pull/25/commits/3fc69a3f0a0bced359fef9c8453015caabc9dffa

@ashkan18 Did you have something else in mind? Like a way to provide a cache store and persist the schema no-matter where and how it's used?

**Comment by ashkan18** [comment]
Thanks @dblock I think solution in #25 is good enough for now, this way even if someone wants to do their own caching with cache store it's possible to do so. Going to close this.
