### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [ashkan18/graphlient#41]

**Comment by dblock** [comment]
@ashkan18 Want to give @yuki24 repo and rubygems permissions to make a release?

**Comment by dblock** [comment]
We have https://github.com/ashkan18/graphlient/blob/master/RELEASING.md

**Comment by ashkan18** [comment]
sure, already added him as collaborator and now adding rubygems permission 🙌

**Comment by ashkan18** [comment]
done

**Comment by yuki24** [comment]
[v0.3.0 is now available on Rubygems.](https://rubygems.org/gems/graphlient/versions/0.3.0)
