### ISSUE TITLE
Mutation

### ISSUE THREAD

**Issue by leoGalani** [ashkan18/graphlient#61]
Hi!

I'm trying to set a mutation as a 'string' but I'm getting `NameError: wrong constant name createSomething`

Here is an example of my code:

```
@client.parse <<-'GRAPHQL'
  mutation createSomething($name: String!, $filter: createSomethingFilterInput!, $frequency: SomethingFrequency!) {
     createSomething(name: $name, filter: $filter, frequency: $frequency) {
     success
     message
     __typename
     }
}
GRAPHQL
```
But the same `mutation` works using graphql playground.
```
  mutation createSomething($name: String!, $filter: createSomethingFilterInput!, $frequency: SomethingFrequency!) {
     createSomething(name: $name, filter: $filter, frequency: $frequency) {
     success
     message
     __typename
     }
}
```

I'm trying to avoid the use of Blocks as I want to maintain a standard on my code.

**Comment by yuki24** [comment]
I'm not sure what you refer to by "as a string", but parsed results can [only be set to constants](https://github.com/github/graphql-client#defining-queries), which in Ruby must start with a capitalized letter. Have you tried renaming `mutation` to `Mutation`?

**Comment by ashkan18** [comment]
this looks ok to me, the only thing I can think of is `'` around `GRAPHQL`, can you try removing that? or switch to something like
```ruby
%(
mutation createSomething($name: String!, $filter: createSomethingFilterInput!, $frequency: SomethingFrequency!) {
     createSomething(name: $name, filter: $filter, frequency: $frequency) {
     success
     message
     __typename
     }
})
```

**Comment by yuki24** [comment]
I should've been more clear on what I was really referring to by `mutation`, but I was referring to the local variable `mutation` in Ruby, not the one in the actual GraphQL query:

```diff
-mutation = @client.parse <<-'GRAPHQL'
+Mutation = @client.parse <<-'GRAPHQL'
```

The single quotes around `GRAPHQL` is valid Ruby syntax:

```ruby
foo = <<-'GRAPHQL'
  text
GRAPHQL
# => "  text\n"
```

**Comment by leoGalani** [comment]
Hello! 
Thanks for the support.
I'm actually using a lambda function to define my constant. The problem is the name of the mutation itself... 
I changed it from `createSomething` to `CreateSomething` (with capital letter) on my mutation request and it works @ graphql playground.

Now I'm getting the following error `expected definition to be a GraphQL::Client::OperationDefinition but was GraphQL::Language::Nodes::Document`

I'm calling this mutation like this:

```
response = @client.query(SomethingQueries::Create.call(@client), variables)
```

Just so you know how I define my Constant :
```
module SomethingQueries
 Create = lambda { |client|
 @client.parse <<-'GRAPHQL'
  mutation CreateSomething($name: String!, $filter: createSomethingFilterInput!, $frequency: SomethingFrequency!) {
     createSomething(name: $name, filter: $filter, frequency: $frequency) {
     success
     message
     __typename
     }
  }
GRAPHQL
}
```

**Comment by leoGalani** [comment]
One thing that I noticed is that when I change the mutation name to use a capital letter, it creates a  `Module` class.
My other queries on the project (to list everything, to find a specific id) are all defined as `GraphQL::Client::OperationDefinition` class.

Not sure its suppose to be like that.

**Comment by ashkan18** [comment]
interesting! so `parse` in `Graphlient` underneath uses [`graphql-client` ](https://github.com/github/graphql-client#defining-queries) to parse the query, if you pass in a block, it will first try to create query string from it and otherwise it will just pass it to the underneath `parse` method. Looking at [their examples](https://github.com/github/graphql-client#defining-queries) i don't  see them using mutation or query alias.

On the other hand, i don't think you'd need that mutation name necessarily, that only changes how you access the results of that mutation and adds a  `createSomething` to response path. so instead of `response.data.data...` you'd access thing using `response.data.create_someting`. Unless you are planning to have multiple mutation per one request, i don't think you'd need that alias. Hope this helps 💚

**Comment by leoGalani** [comment]
My team uses mutation names to track down possible issues @ datadog... if the operation doesn't have a name, it's a bit harder to debug* :)

Thanks again for the support!

**Comment by ashkan18** [comment]
@leoGalani , Sorry haven't had a chance to look at this yet, did you figure out how to fix it? I was hoping to create a failing spec and go from there.

**Comment by leoGalani** [comment]
I didn't have time to stop and look at how the parsing goes.
Once I finish my mid tasks, I will fork your repo and try some stuff out and then come with a PR :)

For now, I don't mind not having an operation name 😅

**Comment by Hareramrai** [comment]
We have an around for this by using https://github.com/tools-aoeur/graphlient/pull/1.

**Comment by trevorh** [comment]
> We have an around for this by using [tools-aoeur#1](https://github.com/tools-aoeur/graphlient/pull/1).

@ashkan18 - this fork works perfectly for me. I was encountering the same issue in trying to use query/mutation aliases and not getting the correct object type back (orphaned Module instance).

I'm guessing that [graphql-client](https://github.com/github-community-projects/graphql-client) doesn't permit them as they expect the constant returned from parsing to function as the alias. However, as others have mentioned, for logging/debuggin/observability, the alias needs to be preserved in whatever is sent for execution.

**Comment by dblock** [comment]
Can someone PR the fix (and other changes on the fork) here?
