### ISSUE TITLE
Make HTTP request stack swappable

### ISSUE THREAD

**Issue by dblock** [ashkan18/graphlient#7]
Bring your own HTTP, inspired by https://github.com/codegram/hyperclient#api-client.

Or maybe replace HTTP for Faraday?

**Comment by ashkan18** [comment]
going to switch our HTTP layer with `graphql-client` so we can also benefit from their schema validation and handle #2

**Comment by dblock** [comment]
You can now do this by subclassing Graphlient::Client and overriding `http`, so really there's only one more step to allow passing `http` in options to swap the default implementation.
