### ISSUE TITLE
Enable the use of FragmentDefinition constants within blocks

### ISSUE THREAD

**Issue by rellampec** [ashkan18/graphlient#93]
**Is your feature request related to a problem? Please describe.**

While `fragments` are backed when you use `heredoc` syntax and `parse` by storing in a constant, using the constant in a `block` will fail with a `"}" (RCURLY)` `GraphQL::ParseError`.

For example, for the following fragment:

```ruby
HumanFragment = graphlient.parse <<-'GRAPHQL'
  fragment on Human {
    name
    homePlanet
  }
GRAPHQL
```

Using it like this will work:

```ruby
HerosQuery = graphlient.parse <<-'GRAPHQL'
  {
    luke: human(id: "1000") {
      ...HumanFragment
    }
    leia: human(id: "1003") {
      ...HumanFragment
    }
  }
GRAPHQL

graphlient.query(HerosQuery)
```

However, when using blocks, we clearly cannot use `...HumanFragment`. Using the constants themselves will fail with a parsing error.

```ruby
graphlient.query {
  luke: human(id: "1000") {
    HumanFragment
  }
  leia: human(id: "1003") {
    HumanFragment
  }
}
```

The error:

```
        11: from ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/graphlient-0.6.0/lib/graphlient/client.rb:37:in `query'
        10: from ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/graphlient-0.6.0/lib/graphlient/client.rb:15:in `parse'
         9: from ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/graphql-client-0.18.0/lib/graphql/client.rb:186:in `parse'
         8: from ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/graphql-2.0.14/lib/graphql.rb:46:in `parse'
         7: from ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/graphql-2.0.14/lib/graphql.rb:58:in `parse_with_racc'
         6: from parser.y:480:in `parse'
         5: from parser.y:466:in `parse_document'
         4: from ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/graphql-2.0.14/lib/graphql/tracing.rb:90:in `trace'
         3: from parser.y:470:in `block in parse_document'
         2: from ruby/Ruby26-x64/lib/ruby/2.6.0/racc/parser.rb:259:in `do_parse'
         1: from ruby/Ruby26-x64/lib/ruby/2.6.0/racc/parser.rb:259:in `_racc_do_parse_c'
parser.y:538:in `on_error': Parse error on "}" (RCURLY) at [4, 13] (GraphQL::ParseError)
```

**Describe the solution you'd like**

I think that to be aligned with the backing gem (`graph-client`) those constants should be usable within the block structure that `graphlient` offers.

```ruby
HumanFragment.class
#GraphQL::Client::FragmentDefinition
```

^ They belong to a well known class. So perhaps they could be just transformed to `...HumanFragment`, so when `Graph::Client.parse` kicks in, finds them the way it expects?

**Describe alternatives you've considered**

Besides what is already offered in the back gem `graphql-client`, there isn't anything in `graphlient` that allows to use fragments with blocks (unless I completely missed this point). The only reference to fragments is [this issue](https://github.com/ashkan18/graphlient/issues/85), and the solution was by not using blocks.

**Additional context**

I think that the above is pretty clear. You may see this is useful or you may see it is not or have another better/easier idea to support fragments. But I do not think the above can be missunderstood.

**Comment by dblock** [comment]
Good idea, try to implement it?

**Comment by rellampec** [comment]
@dblock you're right. Needs to call `Graphlient::Query#method_missing` and using the _constant_ `HumanFragment` as is will delegate to the `GraphQL::Client`.

Well, although the below deviates from the `sym` convention that you took for parameters, this worked fine:

```
graphlient.query {
  luke: human(id: "1000") {
    ___HumanFragment
  }
  leia: human(id: "1003") {
    ___HumanFragment
  }
}
```

And in `Graphlient::Query`, adding this line in the private `append_method`:

```
      node = node.to_s.gsub("___", "...").to_sym if node.to_s.start_with?("___")
```

Perhaps you got a better idea? (it supports fragments by just adding 1 line)

**Comment by rellampec** [comment]
I have actually applied a patch using the above approach.

To support namespaces on fragments

```ruby
module Fragment
  Human = graphlient.parse <<-'GRAPHQL'
    fragment on Human {
      name
      homePlanet
    }
  GRAPHQL
end
```

an additional convention is necessary. Double underscore `__` for double colons `::`, by adding this as first line of the `append_method` private method of `Graphlient::Query`:

```ruby
      node = node.to_s.gsub("___", "...").gsub("__", "::").to_sym.to_sym if node.to_s.start_with?("___")
```

The above allows for this **usage**:

```ruby
graphlient.query {
  luke: human(id: "1000") {
    ___Fragment__Human
  }
  leia: human(id: "1003") {
    ___Fragment__Human
  }
}
```

Which will become the below string in `Graphlient::Client#parse` before `GrapQL::Client#parse` is called:

```graphql
query {
  luke: human(id: "1000") {
    ...Fragment::Human
  }
  leia: human(id: "1003") {
    ...Fragment::Human
  }
}
```

**Comment by dblock** [comment]
Make a PR and we can talk it over there?

**Comment by rellampec** [comment]
@dblock  hmmm, I haven't tried but I was thinking if it wouldn't be cleaner to just

```
module GraphQL
  class Client
    class FragmentDefinition
      self.to_s
        "...#{name}"
      end
    end
  end
end
```

I will give it a try and see if that works

**Comment by rellampec** [comment]
https://github.com/ashkan18/graphlient/pull/94

**Comment by ashkan18** [comment]
@rellampec should we close this?
